services:
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium_chrome
    ports:
      - "4444:4444"  # Porta Selenium RemoteWebDriver

  consumer:
    image: consumer-scraping:latest
    container_name: consumer-data
    depends_on:
      - redis-consumer
      - redis-stream
    environment:
      - REDIS_LOCAL_HOST=redis_consumer
      - REDIS_LOCAL_PORT=6379
    ports:
      - "8080:8080"

  producer:
    image: producer-scraping:latest
    container_name: producer-data
    depends_on:
      - redis-stream
    environment:
      - REDIS_LOCAL_PORT=6379
    ports:
      - "8081:8081"

    #As coisas sairam do controle

  redis-stream:
    image: redis:latest
    ports: [ "6379:6379" ]
    command: redis-server --appendonly yes

  redis-consumer:
    image: redis:latest
    ports:
      - "6380:6380"
    volumes:
      - redis_consumer_data:/data
    command: redis-server --appendonly yes

volumes:
  redis_consumer_data: